In [2]:
import tensorflow as tf

<h3 style='color:Yellow'>Create tf dataset from a list</h3>

In [3]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34,31]

tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

<h3>Iterate through tf dataset</h3>

In [4]:
for sales in tf_dataset:
    print(sales)

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(22, shape=(), dtype=int32)
tf.Tensor(-108, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(32, shape=(), dtype=int32)
tf.Tensor(34, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)


In [8]:
for sales in tf_dataset:
    print(sales.numpy())

21
22
-108
31
-1
32
34
31


In [7]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
-108
31
-1
32
34
31


<h3>Iterate through elements as numpy elements</h3>

In [9]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
-108
31
-1
32
34
31


<h3>Iterate through first n elements in tf dataset</h3>

In [10]:
for sales in tf_dataset.take(3):
    print(sales.numpy())

21
22
-108


<h3>Filter sales numbers that are < 0</h3>

In [11]:
tf_dataset = tf_dataset.filter(lambda x: x>0)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
31
32
34
31


<h3>Convert sales numbers from USA dollars ($) to Indian Rupees (INR) Assuming 1->85 conversation rate</h3>

In [12]:
tf_dataset = tf_dataset.map(lambda x: x*85)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1785
1870
2635
2720
2890
2635


<h3 style='color:skyblue'>Shuffe</h3>

In [ ]:
tf_dataset = tf_dataset.shuffle(2)

for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1785
1870
2635
2720
2635
2890


https://stackoverflow.com/questions/53514495/what-does-batch-repeat-and-shuffle-do-with-tensorflow-dataset

<h3>Batching</h3>

In [236]:
for sales_batch in tf_dataset.batch(2):
    print(sales_batch.numpy())

[1584 2232]
[2304 2448]
[2232 1512]


<h2 style= 'color:yellow'>Perform all of the above operations in one shot</h3>

In [ ]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda y: y*72).shuffle(2).batch(2)

for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[1512 2232]
[1584 2448]
[2304 2232]


<h3>Images</h3>

In [15]:
images_ds = tf.data.Dataset.list_files('flower_photos/flower_photos/*/*', shuffle=False)

In [18]:
for i in images_ds.take(3):
    print(i.numpy())

b'flower_photos\\flower_photos\\daisy\\100080576_f52e8ee070_n.jpg'
b'flower_photos\\flower_photos\\daisy\\10140303196_b88d3d6cec.jpg'
b'flower_photos\\flower_photos\\daisy\\10172379554_b296050f82_n.jpg'


In [16]:
image_count = len(images_ds)
image_count

3670

In [19]:
type(images_ds)

tensorflow.python.data.ops.from_tensor_slices_op._TensorSliceDataset

In [20]:
for file in images_ds.take(3):
    print(file.numpy())

b'flower_photos\\flower_photos\\daisy\\100080576_f52e8ee070_n.jpg'
b'flower_photos\\flower_photos\\daisy\\10140303196_b88d3d6cec.jpg'
b'flower_photos\\flower_photos\\daisy\\10172379554_b296050f82_n.jpg'


In [21]:
images_ds = images_ds.shuffle(200)
for file in images_ds.take(3):
    print(file.numpy())

b'flower_photos\\flower_photos\\daisy\\176375506_201859bb92_m.jpg'
b'flower_photos\\flower_photos\\daisy\\1286274236_1d7ac84efb_n.jpg'
b'flower_photos\\flower_photos\\daisy\\12891819633_e4c82b51e8.jpg'


In [22]:
class_names = ["daisy","dandelion", "roses", "sunflowers", "tulips"]

In [23]:
train_size = int(image_count*0.8)
train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size)

In [25]:
len(train_ds)

2936

In [26]:
len(test_ds)

734

## Get Label

In [28]:
a= 'flower_photos\\flower_photos\\daisy\\176375506_201859bb92_m.jpg'
a.split('\\')[-2]

'daisy'

In [36]:
def get_label(file_path):
    import os
    return tf.strings.split(file_path, os.path.sep)[-2]

In [37]:
train_ds.map(get_label)

<_MapDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>

In [41]:
for i in train_ds.map(get_label):
    print(i.numpy())

b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b'daisy'
b

In [38]:
get_label("images\\dog\\20 Reasons Why Cats Make the Best Pets....jpg")

<tf.Tensor: shape=(), dtype=string, numpy=b'dog'>

In [43]:
a2=tf.io.read_file(a)
tf.image.decode_jpeg(a2)

<tf.Tensor: shape=(240, 180, 3), dtype=uint8, numpy=
array([[[ 36,  49,  23],
        [ 29,  44,  15],
        [ 33,  50,  18],
        ...,
        [ 15,  29,  14],
        [ 21,  35,  22],
        [ 24,  36,  26]],

       [[ 38,  48,  23],
        [ 30,  43,  15],
        [ 33,  50,  18],
        ...,
        [ 17,  31,  14],
        [ 17,  29,  15],
        [ 15,  27,  15]],

       [[ 38,  48,  23],
        [ 29,  42,  14],
        [ 34,  49,  18],
        ...,
        [ 18,  31,  14],
        [ 13,  24,  10],
        [ 10,  20,   9]],

       ...,

       [[160, 161, 156],
        [152, 154, 149],
        [161, 164, 157],
        ...,
        [ 45,  56,  42],
        [ 69,  77,  62],
        [ 62,  68,  54]],

       [[156, 158, 157],
        [159, 161, 156],
        [164, 164, 154],
        ...,
        [ 62,  74,  62],
        [ 71,  81,  70],
        [ 66,  74,  63]],

       [[153, 157, 158],
        [155, 157, 152],
        [162, 160, 148],
        ...,
        [ 67,  83,  7

In [44]:
def process_image(file_path):
    label = get_label(file_path)
    img = tf.io.read_file(file_path) # load the raw data from the file as a string
    img = tf.image.decode_jpeg(img)
    img = tf.image.resize(img, [128, 128])
    return img, label

In [56]:
img, label = process_image(a)
img.numpy()[0]

array([[ 35.364258 ,  47.546875 ,  21.375    ],
       [ 31.608398 ,  47.48535  ,  16.828125 ],
       [ 35.876953 ,  55.538086 ,  16.921875 ],
       [ 43.59375  ,  61.171875 ,  17.90625  ],
       [ 50.6875   ,  66.859375 ,  18.546875 ],
       [ 59.801758 ,  73.77246  ,  21.703125 ],
       [ 66.84863  ,  81.444336 ,  33.929688 ],
       [ 57.40918  ,  75.768555 ,  44.65332  ],
       [ 47.569336 ,  72.25195  ,  32.17383  ],
       [ 40.035156 ,  65.953125 ,  19.126953 ],
       [ 26.375    ,  46.296875 ,  20.84375  ],
       [ 30.574219 ,  45.984375 ,  20.418945 ],
       [ 41.47168  ,  50.993164 ,  25.621094 ],
       [ 32.344727 ,  36.280273 ,  18.992188 ],
       [ 23.39746  ,  29.958008 ,  15.458984 ],
       [ 16.972656 ,  27.638672 ,  11.341797 ],
       [ 18.99414  ,  27.46289  ,   9.452148 ],
       [ 20.399414 ,  30.230469 ,  15.512695 ],
       [ 27.492188 ,  39.58789  ,  20.170898 ],
       [ 28.496094 ,  41.621094 ,  18.089844 ],
       [ 27.08496  ,  39.84082  ,  16.70

In [57]:
train_ds = train_ds.map(process_image)
test_ds = test_ds.map(process_image)

In [58]:
for image, label in train_ds.take(1):
    print("****",image)
    print("****",label)

**** tf.Tensor(
[[[149.57031  101.57031   80.47656 ]
  [147.4862   101.204956  82.84558 ]
  [141.875     98.875     80.10327 ]
  ...
  [169.73438  126.734375 107.734375]
  [172.64062  129.64062  110.640625]
  [176.       131.       112.      ]]

 [[151.71094  103.71094   82.61719 ]
  [149.35156  103.07031   84.71094 ]
  [147.57812  103.15625   84.15625 ]
  ...
  [169.73438  126.734375 109.15625 ]
  [172.64062  129.64062  112.0625  ]
  [176.       130.28906  113.421875]]

 [[153.85156  105.85156   84.75781 ]
  [152.03772  105.75647   87.397095]
  [149.96057  104.96057   84.03943 ]
  ...
  [169.73438  126.734375 109.734375]
  [172.64062  129.64062  112.640625]
  [177.       131.       115.      ]]

 ...

 [[ 43.918823  39.601562  35.83899 ]
  [ 44.08728   43.08728   40.897095]
  [ 57.374634  61.374634  64.15662 ]
  ...
  [ 47.        39.        36.      ]
  [ 46.        38.        35.      ]
  [ 44.        39.        35.      ]]

 [[ 41.03308   40.611206  35.322144]
  [ 38.5813    39.870

In [59]:
def scale(image, label):
    return image/255, label

In [60]:
train_ds = train_ds.map(scale)

In [61]:
for image, label in train_ds.take(5):
    print("****Image: ",image.numpy()[0][0])
    print("****Label: ",label.numpy())

****Image:  [0.01568628 0.04362745 0.        ]
****Label:  b'daisy'
****Image:  [0. 0. 0.]
****Label:  b'daisy'
****Image:  [0.67075676 0.6703891  0.6490043 ]
****Label:  b'daisy'
****Image:  [0.08952206 0.00514706 0.03780637]
****Label:  b'daisy'
****Image:  [0.39421457 0.445195   0.16355005]
****Label:  b'daisy'
